name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - run: echo ::set-env name=foo::this is foo 1
    - run: echo current env.foo ${{ env.foo }}
    - id: composite1
      uses: ./.github/workflows/composite-action
      with:
        your_name: "Octocat"
      env:
        foo: this is foo 2