name: Check PR title
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: echo base ref
        run: |
          echo ${{ github.event.pull_request.base.ref }}
